name = "marco-pages-dev"
pages_build_output_dir = "./dist"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-03-24"

[triggers]
# Schedule cron triggers:
# - At every 3rd minute
# - At 15:00 (UTC) on first day of the month
# - At 23:59 (UTC) on the last weekday of the month
crons = [ "*/3 * * * *", "* * * * *", "59 23 LW * *" ]

[observability]
enabled = true

[[kv_namespaces]]
binding = "CACHE"
id = "7c22395df09a4c89b57aa2972fd9b46a"

[[kv_namespaces]]
binding = "EMAIL"
id = "5892ae4d22754cefba7f832dacab6056"

[[kv_namespaces]]
binding = "PLAYLIST"
id = "b1ce569744a0426ba7da271ff41cf0ca"
