name = "m3o"
main = "./dist/_worker.js"
compatibility_date = "2025-07-30"
compatibility_flags = [ "nodejs_compat" ]
preview_urls = true
workers_dev = true

# custom domains - https://developers.cloudflare.com/workers/configuration/routing/custom-domains/
routes = [
  { pattern = "m3o.tremtec.com", custom_domain = true },
  { pattern = "marco.tremtec.com", custom_domain = true }
]

[assets]
directory = "./dist/"

[observability.logs]
enabled = true

[observability]
enabled = true

[[kv_namespaces]]
binding = "CACHE"
id = "7c22395df09a4c89b57aa2972fd9b46a"

[[kv_namespaces]]
binding = "EMAIL"
id = "5892ae4d22754cefba7f832dacab6056"

[[kv_namespaces]]
binding = "PLAYLIST"
id = "b1ce569744a0426ba7da271ff41cf0ca"
